#
# This is a bsd makefile, it used to build the syslink to the kernel tree
#
# $Id: Makefile,v 1.3 2003/06/10 16:39:45 lha Exp $
#

.PATH: ${foosrc}

PROG= bar

SRCS= foo.c

.include <bsd.own.mk>
.include <bsd.kmod.mk>
