#!/bin/sh
# $Id: HACKING,v 1.37 2006/01/09 08:37:55 tol Exp $
#
# * Configuration stuff
#
# Arla uses GNU autoconf for configuration.  If you want to modify
# configure.in (or acconfig.h) you'll need autoconf 2.53 (or later),
# automake 1.6 (or later), and libtool 1.4a (or later, depending on
# your platform).
#
# If you have trouble, get the latest versions of these packages,
# build them yourself and install them all in the same prefix. Not
# all package systems do this properly.
# (i.e.: ./configure --prefix=$HOME/toolchain && make && make install)
# And export PATH="$HOME/toolchain/bin:$PATH" (or similar).
#
# To re-create the Arla configuration files, run this command:

autoreconf -f -i

# aclocal creates a file `aclocal.m4' from all the tests in the `cf'
# directory.  autoheader will create `include/config.h.in' and autoconf
# the `configure' script.

exit 0
