#!/bin/sh
# $Id: build-emacs,v 1.16 2007/11/24 23:44:15 tol Exp $
if test "X$FAST" != "X" ; then echo "Not running $0" >&4;  exit 0 ; fi
env CONFIGURE_ARGS="--without-x" $SHELL $SHELLVERBOSE $srcdir/generic-build $AFSROOT/stacken.kth.se/ftp/pub/gnu/emacs/emacs-22.1.tar.gz emacs-22.1
