#!/bin/sh
# $Id: copy-and-diff-gnu-mirror,v 1.9 2002/05/07 16:21:07 lha Exp $
if test "X$FAST" != "X" ; then echo "Not running $0" >&4;  exit 0 ; fi
if test "X$LARGE" = "X" ; then echo "Not running large test $0" >&4;  exit 0 ; fi
original=${1-$AFSROOT/stacken.kth.se/ftp/pub}
(cd $original; tar cvf - gnu) 2>&4 | tar xvf - >&4
find gnu -type f -exec cmp '{}' $original/'{}' \;
