#!/bin/sh
# $Id: copy-file-4G,v 1.3 2007/01/12 16:27:55 tol Exp $

if test "X$FAST" != "X" ; then echo "Not running $0" >&4;  exit 0 ; fi
if test "X$LARGE" = "X" ; then echo "Not running large test $0" >&4;  exit 0 ; fi

filename=file.4G
sourcefile=$AFSROOT/stacken.kth.se/ftp/pub/arla/tests/$filename
sha1val=`cat $AFSROOT/stacken.kth.se/ftp/pub/arla/tests/$filename.sha1`

test -f $sourcefile || exit 1
cp $sourcefile . || exit 1
$objdir/sha1sum $filename| grep $sha1val > /dev/null || exit 1
exit 0
