#!/bin/sh
# $Id: find-and-cat-openbsd,v 1.2 2006/10/24 16:33:54 tol Exp $
if test "X$FAST" != "X" ; then echo "Not running $0" >&4;  exit 0 ; fi
if test "X$LARGE" = "X" ; then echo "Not running large test $0" >&4;  exit 0 ; fi

openbsd_ftp_mirror=${1-$AFSROOT/stacken.kth.se/ftp/pub/OpenBSD/3.5/}
find ${openbsd_ftp_mirror} -type f -exec cat '{}' \; > /dev/null
