#!/bin/sh
# $Id: generic-build,v 1.8 2002/12/30 16:12:08 lha Exp $
if test $# -ne 1 -a $# -ne 2; then
  echo "Usage: $0 file [directory]"
  exit 1
fi
filename=$1
if test $# -gt 1; then
  b=$2
else
  b=`basename $filename .tar.gz`
fi
obj=$b-obj

gzip -dc $filename | tar xvf - >&4 2>&4 || exit 1
mkdir $obj || exit 1
cd $obj || exit 1
../$b/configure $CONFIGURE_ARGS >&4 2>&4 || exit 1
make $MAKEFLAGS >&4 2>&4 || exit 1
