#!/bin/sh
# $Id: getdents-and-unlink1,v 1.8 2007/11/24 23:44:17 tol Exp $
if test "X$FAST" != "X" ; then echo "Not running $0" >&4;  exit 0 ; fi
gzip -dc ${AFSROOT}/stacken.kth.se/ftp/pub/gnu/emacs/emacs-22.1.tar.gz |
tar vxf - >&4 2>&1 || exit 1
cd emacs-22.1 || exit 1
$objdir/kill-softer lisp || exit 1
test -d lisp && exit 1
exit 0
