#!/bin/sh
# $Id: kill-mh,v 1.3 2005/01/31 15:48:14 lha Exp $
if test "X$FAST" != "X" ; then echo "Not running $0" >&4;  exit 0 ; fi
tarfile="$AFSROOT/stacken.kth.se/ftp/pub/arla/tests/inbox2.tar.gz"
gzip -dc $tarfile | tar xf -
cd inbox || exit 1
rm \#*
(ls -1 * | wc -l | grep '20') > /dev/null || exit 1
