#!/bin/sh
# $Id: large-dir-extra,v 1.3 2002/05/07 16:21:09 lha Exp $
if test "X$FAST" != "X" ; then echo "Not running $0" >&4;  exit 0 ; fi
for i in 10 20 30 31 40 50 60 70 80 90 100; do
  $objdir/large-dir2 large-dir-$i $i || exit 1
  $objdir/large-dir3 large-dir-$i $i || exit 1
done
