#!/bin/sh
# $Id: parallel-read,v 1.3 2007/11/24 23:44:17 tol Exp $
FS=${FS:-${objdir}/../appl/fs/fs}
FILE=$AFSROOT/stacken.kth.se/ftp/pub/gnu/emacs/emacs-22.1.tar.gz
${FS} flush $FILE

#see if parallel fetches cause deadlock
for i in 1 2 3; do
  dd if=$FILE bs=64k count=10 > /dev/null >&4 2>&4 &
done

wait
